### ISSUE TITLE
adding tanks doesnt work

### ISSUE THREAD

**Issue by areteta** [przemyslaw-zan/WT-Tech-Tree-Maker#4]
After adding the first tank, adding any after no matter what options or descriptions or images i put, it will not appear. If i try pressing one of the options in settings, it does, but i cannot edit, delete nor use for any following tanks. If i refresh the site it will disappear and any effort spent making it for the tech tree is wasted

**Comment by przemyslaw-zan** [comment]
Hi there!

The tool works for me. Could you please open the console of your web browser (google how to if you don't know how) and see what, if any, errors are appearing as you are trying to add something? You can ignore errors which are there from the beginning about cookies or insecure versions.

Also, what web browser / operating system are you using?

**Comment by areteta** [comment]
I am using Opera GX as my browser.

![image_2024-12-04_212507446](https://github.com/user-attachments/assets/27c75e3e-a726-4127-9ac3-4a817a757b30)
^ I believe these are the errors (happened right now as i tried adding a new tank)

**Comment by przemyslaw-zan** [comment]
Looks like your local storage is full for whatever reason. Did you copy and paste some really long text into the input field by any chance?

Try opening the tool in incognito/private browser window and see if the same thing happens. If not, then perhaps clearing your browser local storage / cache might help.

**Comment by areteta** [comment]
Sorry for late reply, but it still doesn't work on normal browser after i cleared some of the data.

However it does work on incognito so i guess i'll try using it there
Thanks for the help!

**Comment by areteta** [comment]
I've re-opened the issue as it also has stopped working on incognito tabs.

It might be something to do with the script, but its just not working for me.

**Comment by areteta** [comment]
![image](https://github.com/user-attachments/assets/a63df671-f398-46ed-a436-a3a2ada9c48d)
Is this what your looking for?

**Comment by przemyslaw-zan** [comment]
Yeah, looks fine. Not sure how to help you at this point, Other than perhaps suggesting using another browser. Sorry that I could not help :/

**Comment by areteta** [comment]
Alright then, thanks anyway
